name: Android CI
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test unitaire API
        run: ./gradlew testDebugUnitTest
        continue-on-error: true
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0